"""initial_schema

Revision ID: aa0742f72386
Revises: 
Create Date: 2025-12-23 14:03:03.425044
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic
revision: str = 'aa0742f72386'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: initial_schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_organizations_user_id', 'organizations', ['user_id'], unique=False)
    op.create_table('calculated_metrics',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('total_cash', sa.Numeric(precision=15, scale=2), nullable=True, comment='Sum of all bank account balances'),
    sa.Column('total_receivables', sa.Numeric(precision=15, scale=2), nullable=True, comment='Outstanding accounts receivable (AR)'),
    sa.Column('total_payables', sa.Numeric(precision=15, scale=2), nullable=True, comment='Outstanding accounts payable (AP)'),
    sa.Column('burn_rate_monthly', sa.Numeric(precision=15, scale=2), nullable=True, comment='Average monthly net loss (positive = burning cash)'),
    sa.Column('runway_months', sa.Numeric(precision=6, scale=2), nullable=True, comment='Months until cash runs out (null if profitable)'),
    sa.Column('revenue_monthly', sa.Numeric(precision=15, scale=2), nullable=True, comment='Average monthly revenue'),
    sa.Column('expenses_monthly', sa.Numeric(precision=15, scale=2), nullable=True, comment='Average monthly expenses'),
    sa.Column('net_income_monthly', sa.Numeric(precision=15, scale=2), nullable=True, comment='Average monthly net income (negative = loss)'),
    sa.Column('expense_trend_percent', sa.Numeric(precision=6, scale=2), nullable=True, comment='Month-over-month expense change percentage'),
    sa.Column('revenue_trend_percent', sa.Numeric(precision=6, scale=2), nullable=True, comment='Month-over-month revenue change percentage'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI-generated 2-sentence health summary'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='Risk classification: low, medium, high, critical'),
    sa.Column('action_item', sa.Text(), nullable=True, comment='AI-generated recommended action'),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False, comment='When metrics were calculated'),
    sa.Column('data_period_start', sa.DateTime(timezone=True), nullable=True, comment='Start of data period used for calculations'),
    sa.Column('data_period_end', sa.DateTime(timezone=True), nullable=True, comment='End of data period used for calculations'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index('ix_calculated_metrics_organization_id', 'calculated_metrics', ['organization_id'], unique=False)
    op.create_index('ix_calculated_metrics_risk_level', 'calculated_metrics', ['risk_level'], unique=False)
    op.create_table('financial_caches',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('bank_accounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Bank account balances and details'),
    sa.Column('bank_transactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Recent bank transactions'),
    sa.Column('invoices_receivable', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Accounts receivable (AR) invoices'),
    sa.Column('invoices_payable', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Accounts payable (AP) invoices'),
    sa.Column('profit_loss_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Profit & Loss report data'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='When data was fetched from Xero'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When cache expires (fetched_at + TTL)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index('ix_financial_caches_expires_at', 'financial_caches', ['expires_at'], unique=False)
    op.create_index('ix_financial_caches_organization_id', 'financial_caches', ['organization_id'], unique=False)
    op.create_table('xero_tokens',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('xero_tenant_id', sa.String(length=255), nullable=False, comment="Xero's internal organization identifier"),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('id_token', sa.Text(), nullable=True, comment='OIDC identity token'),
    sa.Column('token_type', sa.String(length=50), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False, comment='Space-separated OAuth scopes'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When access_token expires'),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_api_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_index('ix_xero_tokens_expires_at', 'xero_tokens', ['expires_at'], unique=False)
    op.create_index('ix_xero_tokens_organization_id', 'xero_tokens', ['organization_id'], unique=False)
    op.create_index('ix_xero_tokens_status', 'xero_tokens', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: initial_schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_xero_tokens_status', table_name='xero_tokens')
    op.drop_index('ix_xero_tokens_organization_id', table_name='xero_tokens')
    op.drop_index('ix_xero_tokens_expires_at', table_name='xero_tokens')
    op.drop_table('xero_tokens')
    op.drop_index('ix_financial_caches_organization_id', table_name='financial_caches')
    op.drop_index('ix_financial_caches_expires_at', table_name='financial_caches')
    op.drop_table('financial_caches')
    op.drop_index('ix_calculated_metrics_risk_level', table_name='calculated_metrics')
    op.drop_index('ix_calculated_metrics_organization_id', table_name='calculated_metrics')
    op.drop_table('calculated_metrics')
    op.drop_index('ix_organizations_user_id', table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

