"""add_executive_summary_cache_and_update_financial_cache

Revision ID: 681462e5a334
Revises: aa0742f72386
Create Date: 2025-12-24 20:06:17.253551
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic
revision: str = '681462e5a334'
down_revision: Union[str, None] = 'aa0742f72386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: add_executive_summary_cache_and_update_financial_cache"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executive_summary_caches',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False, comment='Month-end date identifying the month (e.g., 2025-11-30)'),
    sa.Column('cash_position', sa.Numeric(precision=15, scale=2), nullable=False, comment='Closing bank balance for the month'),
    sa.Column('cash_spent', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total cash spent in the month'),
    sa.Column('cash_received', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total cash received in the month'),
    sa.Column('operating_expenses', sa.Numeric(precision=15, scale=2), nullable=False, comment='Total operating expenses for the month'),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full Executive Summary report structure (for debugging)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='When data was fetched from Xero'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'report_date', name='uq_exec_summary_org_date')
    )
    op.create_index('ix_exec_summary_org_date', 'executive_summary_caches', ['organization_id', 'report_date'], unique=False)
    op.create_index(op.f('ix_executive_summary_caches_organization_id'), 'executive_summary_caches', ['organization_id'], unique=False)
    op.add_column('financial_caches', sa.Column('executive_summary_current', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Current month Executive Summary data (incomplete month)'))
    op.add_column('financial_caches', sa.Column('executive_summary_current_fetched_at', sa.DateTime(timezone=True), nullable=True, comment='When current Executive Summary was fetched'))
    op.add_column('financial_caches', sa.Column('executive_summary_current_expires_at', sa.DateTime(timezone=True), nullable=True, comment='When current Executive Summary expires'))
    op.alter_column('financial_caches', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='When receivables/payables/P&L were fetched',
               existing_comment='When data was fetched from Xero')
    op.alter_column('financial_caches', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               comment='When receivables/payables/P&L cache expires',
               existing_comment='When cache expires (fetched_at + TTL)')
    op.drop_column('financial_caches', 'bank_accounts')
    op.drop_column('financial_caches', 'bank_transactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: add_executive_summary_cache_and_update_financial_cache"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial_caches', sa.Column('bank_transactions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Recent bank transactions'))
    op.add_column('financial_caches', sa.Column('bank_accounts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Bank account balances and details'))
    op.alter_column('financial_caches', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='When cache expires (fetched_at + TTL)',
               existing_comment='When receivables/payables/P&L cache expires')
    op.alter_column('financial_caches', 'fetched_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               comment='When data was fetched from Xero',
               existing_comment='When receivables/payables/P&L were fetched')
    op.drop_column('financial_caches', 'executive_summary_current_expires_at')
    op.drop_column('financial_caches', 'executive_summary_current_fetched_at')
    op.drop_column('financial_caches', 'executive_summary_current')
    op.drop_index(op.f('ix_executive_summary_caches_organization_id'), table_name='executive_summary_caches')
    op.drop_index('ix_exec_summary_org_date', table_name='executive_summary_caches')
    op.drop_table('executive_summary_caches')
    # ### end Alembic commands ###

