"""add_auth_security_tables

Revision ID: 22207bb53458
Revises: 681462e5a334
Create Date: 2025-12-24 21:46:47.544598
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic
revision: str = '22207bb53458'
down_revision: Union[str, None] = '681462e5a334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: add_auth_security_tables"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email address used in login attempt'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User ID if user exists (null for non-existent users)'),
    sa.Column('ip_address', sa.String(length=45), nullable=False, comment='IP address of the login attempt (supports IPv6)'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the login was successful'),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False, comment='When the attempt was made'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_login_attempt_email_time', 'login_attempts', ['email', 'attempted_at'], unique=False)
    op.create_index('ix_login_attempt_ip_time', 'login_attempts', ['ip_address', 'attempted_at'], unique=False)
    op.create_index('ix_login_attempt_user_time', 'login_attempts', ['user_id', 'attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_attempted_at'), 'login_attempts', ['attempted_at'], unique=False)
    op.create_index(op.f('ix_login_attempts_email'), 'login_attempts', ['email'], unique=False)
    op.create_index(op.f('ix_login_attempts_ip_address'), 'login_attempts', ['ip_address'], unique=False)
    op.create_index(op.f('ix_login_attempts_success'), 'login_attempts', ['success'], unique=False)
    op.create_index(op.f('ix_login_attempts_user_id'), 'login_attempts', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of the refresh token'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who owns this token'),
    sa.Column('is_used', sa.Boolean(), nullable=False, comment='Whether this token has been used (one-time use)'),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False, comment='When the token was issued'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When the token expires'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='When the token was used (if used)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_refresh_token_user_expires', 'refresh_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_index('ix_refresh_token_user_used', 'refresh_tokens', ['user_id', 'is_used'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_used'), 'refresh_tokens', ['is_used'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_issued_at'), 'refresh_tokens', ['issued_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('token_blacklists',
    sa.Column('jti', sa.String(length=255), nullable=False, comment='JWT ID (unique token identifier)'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='SHA256 hash of the full token for quick lookup'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who owns this token'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False, comment='When the token was revoked'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When the token naturally expires (from JWT exp claim)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_token_blacklist_expires', 'token_blacklists', ['expires_at'], unique=False)
    op.create_index('ix_token_blacklist_user_expires', 'token_blacklists', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklists_expires_at'), 'token_blacklists', ['expires_at'], unique=False)
    op.create_index(op.f('ix_token_blacklists_jti'), 'token_blacklists', ['jti'], unique=True)
    op.create_index(op.f('ix_token_blacklists_token_hash'), 'token_blacklists', ['token_hash'], unique=False)
    op.create_index(op.f('ix_token_blacklists_user_id'), 'token_blacklists', ['user_id'], unique=False)
    # Add failed_login_attempts with default value for existing rows
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True, comment='Number of consecutive failed login attempts'))
    op.execute("UPDATE users SET failed_login_attempts = 0 WHERE failed_login_attempts IS NULL")
    op.alter_column('users', 'failed_login_attempts', nullable=False, server_default='0')
    
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this timestamp (null if not locked)'))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp'))
    op.create_index(op.f('ix_users_locked_until'), 'users', ['locked_until'], unique=False)
    
    # Add foreign key constraints for new tables
    op.create_foreign_key('fk_login_attempts_user_id', 'login_attempts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_refresh_tokens_user_id', 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_token_blacklists_user_id', 'token_blacklists', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: add_auth_security_tables"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_token_blacklists_user_id', 'token_blacklists', type_='foreignkey')
    op.drop_constraint('fk_refresh_tokens_user_id', 'refresh_tokens', type_='foreignkey')
    op.drop_constraint('fk_login_attempts_user_id', 'login_attempts', type_='foreignkey')
    op.drop_index(op.f('ix_users_locked_until'), table_name='users')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'locked_until')
    op.alter_column('users', 'failed_login_attempts', nullable=True, server_default=None)
    op.drop_column('users', 'failed_login_attempts')
    op.drop_index(op.f('ix_token_blacklists_user_id'), table_name='token_blacklists')
    op.drop_index(op.f('ix_token_blacklists_token_hash'), table_name='token_blacklists')
    op.drop_index(op.f('ix_token_blacklists_jti'), table_name='token_blacklists')
    op.drop_index(op.f('ix_token_blacklists_expires_at'), table_name='token_blacklists')
    op.drop_index('ix_token_blacklist_user_expires', table_name='token_blacklists')
    op.drop_index('ix_token_blacklist_expires', table_name='token_blacklists')
    op.drop_table('token_blacklists')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_issued_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_used'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_user_used', table_name='refresh_tokens')
    op.drop_index('ix_refresh_token_user_expires', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_login_attempts_user_id'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_success'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_ip_address'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_email'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_attempted_at'), table_name='login_attempts')
    op.drop_index('ix_login_attempt_user_time', table_name='login_attempts')
    op.drop_index('ix_login_attempt_ip_time', table_name='login_attempts')
    op.drop_index('ix_login_attempt_email_time', table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###

