"""add_insight_feedback_and_insight_id

Revision ID: 3d12051ae29e
Revises: ea79455ca6a0
Create Date: 2026-01-06 17:19:47.798414
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic
revision: str = '3d12051ae29e'
down_revision: Union[str, None] = 'ea79455ca6a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: add_insight_feedback_and_insight_id"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insight_feedbacks',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('insight_id', sa.String(length=255), nullable=False, comment='Reference to insight (insight.insight_id)'),
    sa.Column('insight_type', sa.String(length=50), nullable=False, comment='Type of insight (snapshot)'),
    sa.Column('insight_title', sa.Text(), nullable=False, comment='Title of insight (snapshot)'),
    sa.Column('is_helpful', sa.Boolean(), nullable=False, comment='Whether insight was helpful (true) or not helpful (false)'),
    sa.Column('comment', sa.Text(), nullable=True, comment='Optional user comment (max 500 chars)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insight_feedback_insight_id', 'insight_feedbacks', ['insight_id'], unique=False)
    op.create_index('ix_insight_feedback_insight_type', 'insight_feedbacks', ['insight_type'], unique=False)
    op.create_index('ix_insight_feedback_is_helpful', 'insight_feedbacks', ['is_helpful'], unique=False)
    op.create_index('ix_insight_feedback_organization_id', 'insight_feedbacks', ['organization_id'], unique=False)
    op.create_index('ix_insight_feedback_user_id', 'insight_feedbacks', ['user_id'], unique=False)
    op.create_index('ix_insight_feedback_user_insight', 'insight_feedbacks', ['user_id', 'insight_id'], unique=True)
    op.create_index(op.f('ix_insight_feedbacks_insight_id'), 'insight_feedbacks', ['insight_id'], unique=False)
    op.create_index(op.f('ix_insight_feedbacks_insight_type'), 'insight_feedbacks', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insight_feedbacks_is_helpful'), 'insight_feedbacks', ['is_helpful'], unique=False)
    op.create_index(op.f('ix_insight_feedbacks_organization_id'), 'insight_feedbacks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_insight_feedbacks_user_id'), 'insight_feedbacks', ['user_id'], unique=False)
    op.add_column('insights', sa.Column('insight_id', sa.String(length=255), nullable=False, comment='Unique insight identifier (UUID string from generator)'))
    op.create_index('ix_insights_insight_id', 'insights', ['insight_id'], unique=False)
    op.create_index('ix_insights_org_insight_id', 'insights', ['organization_id', 'insight_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: add_insight_feedback_and_insight_id"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insights_org_insight_id', table_name='insights')
    op.drop_index('ix_insights_insight_id', table_name='insights')
    op.drop_column('insights', 'insight_id')
    op.drop_index(op.f('ix_insight_feedbacks_user_id'), table_name='insight_feedbacks')
    op.drop_index(op.f('ix_insight_feedbacks_organization_id'), table_name='insight_feedbacks')
    op.drop_index(op.f('ix_insight_feedbacks_is_helpful'), table_name='insight_feedbacks')
    op.drop_index(op.f('ix_insight_feedbacks_insight_type'), table_name='insight_feedbacks')
    op.drop_index(op.f('ix_insight_feedbacks_insight_id'), table_name='insight_feedbacks')
    op.drop_index('ix_insight_feedback_user_insight', table_name='insight_feedbacks')
    op.drop_index('ix_insight_feedback_user_id', table_name='insight_feedbacks')
    op.drop_index('ix_insight_feedback_organization_id', table_name='insight_feedbacks')
    op.drop_index('ix_insight_feedback_is_helpful', table_name='insight_feedbacks')
    op.drop_index('ix_insight_feedback_insight_type', table_name='insight_feedbacks')
    op.drop_index('ix_insight_feedback_insight_id', table_name='insight_feedbacks')
    op.drop_table('insight_feedbacks')
    # ### end Alembic commands ###

