"""add_metrics_payload

Revision ID: 9a5a7c124b69
Revises: 4b715a96b29a
Create Date: 2026-01-07 16:19:32.381776
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic
revision: str = '9a5a7c124b69'
down_revision: Union[str, None] = '4b715a96b29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: add_metrics_payload"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculated_metrics', sa.Column('metrics_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Full JSON payload of calculated metrics for dashboard display'))
    op.drop_index('ix_insights_insight_id', table_name='insights')
    op.create_index(op.f('ix_insights_insight_id'), 'insights', ['insight_id'], unique=True)
    op.alter_column('organizations', 'sync_status',
               existing_type=postgresql.ENUM('IDLE', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='sync_status_enum'),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: add_metrics_payload"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'sync_status',
               existing_type=postgresql.ENUM('IDLE', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='sync_status_enum'),
               server_default=sa.text("'IDLE'::sync_status_enum"),
               existing_nullable=False)
    op.drop_index(op.f('ix_insights_insight_id'), table_name='insights')
    op.create_index('ix_insights_insight_id', 'insights', ['insight_id'], unique=False)
    op.drop_column('calculated_metrics', 'metrics_payload')
    # ### end Alembic commands ###

