"""add_insight_table

Revision ID: ea79455ca6a0
Revises: 343c3cbcfbf6
Create Date: 2026-01-06 15:58:00.530842
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic
revision: str = 'ea79455ca6a0'
down_revision: Union[str, None] = '343c3cbcfbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: add_insight_table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insights',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=False, comment='Type of insight (cash_runway_risk, upcoming_cash_squeeze, etc.)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Plain-English headline'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Severity level: high, medium, or low'),
    sa.Column('confidence_level', sa.String(length=20), nullable=False, comment='Confidence level: high, medium, or low'),
    sa.Column('summary', sa.Text(), nullable=False, comment="1-2 sentence summary of what's happening"),
    sa.Column('why_it_matters', sa.Text(), nullable=False, comment='Short paragraph explaining why this matters now'),
    sa.Column('recommended_actions', sa.JSON(), nullable=False, comment='List of actionable steps (3-5 items)'),
    sa.Column('supporting_numbers', sa.JSON(), nullable=True, comment='Key numbers supporting the insight'),
    sa.Column('data_notes', sa.Text(), nullable=True, comment='Optional notes about data quality or limitations'),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False, comment='Whether user has acknowledged this insight'),
    sa.Column('is_marked_done', sa.Boolean(), nullable=False, comment='Whether user has marked this as done'),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True, comment='When insight was acknowledged'),
    sa.Column('marked_done_at', sa.DateTime(timezone=True), nullable=True, comment='When insight was marked as done'),
    sa.Column('acknowledged_by_user_id', sa.UUID(), nullable=True, comment='User who acknowledged this insight'),
    sa.Column('marked_done_by_user_id', sa.UUID(), nullable=True, comment='User who marked this insight as done'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False, comment='When insight was generated'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acknowledged_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['marked_done_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_insights_acknowledged', 'insights', ['is_acknowledged'], unique=False)
    op.create_index('ix_insights_generated_at', 'insights', ['generated_at'], unique=False)
    op.create_index(op.f('ix_insights_insight_type'), 'insights', ['insight_type'], unique=False)
    op.create_index(op.f('ix_insights_is_acknowledged'), 'insights', ['is_acknowledged'], unique=False)
    op.create_index(op.f('ix_insights_is_marked_done'), 'insights', ['is_marked_done'], unique=False)
    op.create_index('ix_insights_marked_done', 'insights', ['is_marked_done'], unique=False)
    op.create_index('ix_insights_organization_id', 'insights', ['organization_id'], unique=False)
    op.create_index('ix_insights_severity', 'insights', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: add_insight_table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_insights_severity', table_name='insights')
    op.drop_index('ix_insights_organization_id', table_name='insights')
    op.drop_index('ix_insights_marked_done', table_name='insights')
    op.drop_index(op.f('ix_insights_is_marked_done'), table_name='insights')
    op.drop_index(op.f('ix_insights_is_acknowledged'), table_name='insights')
    op.drop_index(op.f('ix_insights_insight_type'), table_name='insights')
    op.drop_index('ix_insights_generated_at', table_name='insights')
    op.drop_index('ix_insights_acknowledged', table_name='insights')
    op.drop_table('insights')
    # ### end Alembic commands ###

