"""add_sync_status

Revision ID: 4b715a96b29a
Revises: 3d12051ae29e
Create Date: 2026-01-07 15:11:22.918702
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic
revision: str = '4b715a96b29a'
down_revision: Union[str, None] = '3d12051ae29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: add_sync_status"""
    
    # Define the Enums
    sync_status_enum = sa.Enum('IDLE', 'IN_PROGRESS', 'COMPLETED', 'FAILED', name='sync_status_enum')
    sync_step_enum = sa.Enum('CONNECTING', 'IMPORTING', 'CALCULATING', 'GENERATING_INSIGHTS', 'COMPLETED', name='sync_step_enum')
    
    # Create the Types explicitly
    sync_status_enum.create(op.get_bind(), checkfirst=True)
    sync_step_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('sync_status', sync_status_enum, nullable=False, server_default='IDLE'))
    op.add_column('organizations', sa.Column('sync_step', sync_step_enum, nullable=True))
    op.add_column('organizations', sa.Column('last_sync_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: add_sync_status"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'last_sync_error')
    op.drop_column('organizations', 'sync_step')
    op.drop_column('organizations', 'sync_status')
    # ### end Alembic commands ###
    
    # Drop the Types
    sync_status_enum = sa.Enum(name='sync_status_enum')
    sync_step_enum = sa.Enum(name='sync_step_enum')
    
    sync_status_enum.drop(op.get_bind(), checkfirst=True)
    sync_step_enum.drop(op.get_bind(), checkfirst=True)
