"""add_profit_loss_cache_table

Revision ID: 343c3cbcfbf6
Revises: 22207bb53458
Create Date: 2026-01-06 11:01:52.781384
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic
revision: str = '343c3cbcfbf6'
down_revision: Union[str, None] = '22207bb53458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration: add_profit_loss_cache_table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profit_loss_caches',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False, comment='P&L period start date'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='P&L period end date'),
    sa.Column('profit_loss_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Cached Profit & Loss report data'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='When data was fetched from Xero'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='When cache expires (fetched_at + TTL)'),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'start_date', 'end_date', name='uq_profit_loss_cache_org_dates')
    )
    op.create_index('ix_profit_loss_cache_expires_at', 'profit_loss_caches', ['expires_at'], unique=False)
    op.create_index('ix_profit_loss_cache_org_dates', 'profit_loss_caches', ['organization_id', 'start_date', 'end_date'], unique=False)
    op.create_index(op.f('ix_profit_loss_caches_expires_at'), 'profit_loss_caches', ['expires_at'], unique=False)
    op.create_index(op.f('ix_profit_loss_caches_organization_id'), 'profit_loss_caches', ['organization_id'], unique=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='Number of consecutive failed login attempts',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration: add_profit_loss_cache_table"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_comment='Number of consecutive failed login attempts',
               existing_nullable=False)
    op.drop_index(op.f('ix_profit_loss_caches_organization_id'), table_name='profit_loss_caches')
    op.drop_index(op.f('ix_profit_loss_caches_expires_at'), table_name='profit_loss_caches')
    op.drop_index('ix_profit_loss_cache_org_dates', table_name='profit_loss_caches')
    op.drop_index('ix_profit_loss_cache_expires_at', table_name='profit_loss_caches')
    op.drop_table('profit_loss_caches')
    # ### end Alembic commands ###

